name: Build Needle SDK Typescript

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-needle-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.1.13"

      - name: Build needle-sdk
        run: bun i && bun run build
